default_agent: agentcore_strands
agents:
  agentcore_strands:
    name: agentcore_strands
    entrypoint: /Users/ramvegiraju/Desktop/Projects/strands-agent-samples/intro-concepts/BedrockAgentCore-Runtime/strands_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::717279734106:role/agentcore-agentcore_strands-role
      execution_role_auto_create: false
      account: '717279734106'
      region: us-east-1
      ecr_repository: 717279734106.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_strands-65U50G8evH
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:717279734106:runtime/agentcore_strands-65U50G8evH
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcore_strands-builder
      execution_role: arn:aws:iam::717279734106:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-5b70b9d456
      source_bucket: bedrock-agentcore-codebuild-sources-717279734106-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
  my_production_agent:
    name: my_production_agent
    entrypoint: strands_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '717279734106'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
